runtime: python37

automatic_scaling:
  target_cpu_utilization: 0.7
  min_instances: 1
  max_instances: 15

instance_class: F4_1G

inbound_services:
  - warmup

resources:
  cpu: 2
  memory_gb: 4

env_variables: 
  NLTK_DATA: './nltk_data/'